'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{_electron}=require('playwright');
const out=process.env.SHOWDOWN_TEST_OUTPUT||path.resolve('test-results/0.5.9'),sleep=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(out,{recursive:true});
(async()=>{
 const env={...process.env,DFY_PLAY_HOME:out+'/layout-data',DFY_PLAY_CACHE:out+'/layout-cache'};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:process.env.SHOWDOWN_TEST_EXE||path.resolve('node_modules/electron/dist/electron.exe'),args:process.env.SHOWDOWN_TEST_EXE?[]:[path.resolve('.')],env});
 const page=await app.firstWindow(),report=[];let room='';
 const run=code=>app.evaluate(async({webContents},code)=>{const w=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com'));w?.setBackgroundThrottling(false);return w?.executeJavaScript('(()=>{try{return ('+code+')}catch(e){return {fixtureError:e.stack}}})()');},code);
 const until=async code=>{for(let i=0;i<120;i++){try{const r=await run(code);if(r?.fixtureError)throw Error(r.fixtureError);if(r)return;}catch(e){if(!/Execution context was destroyed/.test(e.message))throw e;}await sleep(250);}throw Error('Timed out '+code);};
 const receive=lines=>run('app.receive('+JSON.stringify('>'+room+'\n'+lines.join('\n'))+')');
 const capture=async name=>{await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.restore();w.show();w.focus();});for(let i=0;i<50;i++){await sleep(150);const b64=await app.evaluate(async({webContents})=>(await webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com')).capturePage()).toPNG().toString('base64'));const bytes=Buffer.from(b64,'base64');if(bytes.length>1000){fs.writeFileSync(out+'/'+name+'.png',bytes);return;}}throw Error('Empty screenshot '+name);};
 try{
  await until('!!(window.app&&window.__dfyGame&&window.Battle)');await run('(()=>{app.send=()=>{};return true})()');
  // Normal game navigation stays inside the desktop shell.
  await until("!!document.querySelector('.dfy-game-navigation [data-shell-page=accounts]')");
  await run(`(()=>{document.querySelector('.dfy-game-navigation [data-shell-page=accounts]').click();return true})()`);
  await page.waitForSelector('[data-page="accounts"][aria-current="true"]');await page.click('[data-page=battle]');await sleep(300);
  await run(`(()=>{app.addPopup(TeamPopup,{format:'gen9ou',team:'-1'});return true})()`);await until("!!document.querySelector('.ps-popup [name=teambuilder]')");await run(`(()=>{document.querySelector('.ps-popup [name=teambuilder]').click();return true})()`);await page.waitForSelector('[data-page=teams][aria-current=true]');await page.click('[data-page=battle]');await sleep(300);
  for(const [id,picked,doubles]of [['66',6,false],['64',4,true],['63',3,false]]){
   room='battle-gen9ou-locallayout'+id;const team=['Rotom-Wash','Gholdengo','Incineroar','Rillaboom','Urshifu-Rapid-Strike','Calyrex-Ice'],foe=['Kyogre','Tornadus','Amoonguss','Incineroar','Rillaboom','Miraidon'];
   const mons=(names,active=false)=>names.map((name,i)=>({ident:'p1: '+name,details:name+', L50',condition:'200/200',active:active&&i<(doubles?2:1),moves:['thunderbolt','hydropump','protect','voltswitch'],stats:{atk:120,def:120,spa:160,spd:120,spe:140},baseAbility:'levitate',item:'',teraType:'Grass'}));
   await receive(['|init|battle','|title|布局检查 '+id,'|gametype|'+(doubles?'doubles':'singles'),'|gen|9','|tier|'+(id==='66'?'[Gen 9] OU':id==='64'?'[Gen 9] VGC 2025 Reg I':'[Gen 9] Battle Stadium Singles'),'|player|p1|布局甲|1','|player|p2|布局乙|2','|teamsize|p1|6','|teamsize|p2|6',...team.map(n=>'|poke|p1|'+n+', L50'),...foe.map(n=>'|poke|p2|'+n+', L50'),'|teampreview|'+picked]);
   await run(`app.focusRoom('${room}')`);await receive(['|request|'+JSON.stringify({rqid:1,teamPreview:true,maxTeamSize:picked,side:{name:'布局甲',id:'p1',pokemon:mons(team)}})]);await until(`document.getElementById('room-${room}').querySelectorAll('[data-order-slot]').length===${picked}`);
   for(const [w,h]of [[1440,960],[1100,720]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[w,h]);await sleep(350);await capture('layout-'+id+'-preview-'+w);assert.equal(await run(`document.getElementById('room-${room}').querySelectorAll('.dfy-preview-team').length`),1);}
   await run(`(()=>{const root=document.getElementById('room-${room}');window.__entryProbe={balls:0,extras:0};window.__entryObserver?.disconnect();window.__entryObserver=new MutationObserver(records=>{for(const record of records)for(const n of record.addedNodes){if(n.nodeType!==1)continue;const nodes=[n,...n.querySelectorAll('*')];for(const x of nodes){if(x.matches('img')&&x.getAttribute('src')?.endsWith('/fx/pokeball.png'))window.__entryProbe.balls++;if(x.matches('.dfy-fx-ball'))window.__entryProbe.extras++;}}});window.__entryObserver.observe(root,{childList:true,subtree:true});return true})()`);
   await receive(['|start','|switch|p1a: Rotom-Wash|Rotom-Wash, L50|200/200',...(doubles?['|switch|p1b: Gholdengo|Gholdengo, L50|200/200']:[]),'|switch|p2a: Kyogre|Kyogre, L50|100/100',...(doubles?['|switch|p2b: Tornadus|Tornadus, L50|100/100']:[]),'|turn|1']);
   await until('window.__entryProbe.balls>0');await capture('layout-'+id+'-entry');
   const active={moves:[{move:'Thunderbolt',id:'thunderbolt',pp:16,maxpp:16,target:'normal'},{move:'Hydro Pump',id:'hydropump',pp:8,maxpp:8,target:'normal'},{move:'Protect',id:'protect',pp:16,maxpp:16,target:'self'},{move:'Volt Switch',id:'voltswitch',pp:16,maxpp:16,target:'normal'}],canTerastallize:'Grass'};
   await receive(['|request|'+JSON.stringify({rqid:2,active:Array.from({length:doubles?2:1},()=>active),side:{name:'布局甲',id:'p1',pokemon:mons(team.slice(0,picked),true)}})]);await until(`app.rooms['${room}'].battle.atQueueEnd`);await sleep(500);const entry=await run('window.__entryProbe');assert.equal(entry.balls,doubles?4:2,'Exactly one native ball per entering Pokemon');assert.equal(entry.extras,0,'No additional ball layer');fs.writeFileSync(out+'/entry-'+id+'.json',JSON.stringify(entry));
   for(const [w,h]of [[1920,1080],[1440,960],[1100,720]]){
    await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[w,h]);await sleep(350);await capture('layout-'+id+'-battle-'+w);
    const geometry=await run(`(()=>{const root=document.getElementById('room-${room}'),r=n=>{const x=n.getBoundingClientRect();return {x:x.x,y:x.y,w:x.width,h:x.height,right:x.right,bottom:x.bottom}},b=app.rooms['${room}'].battle;return {arena:r(root.querySelector('.dfy-game-arena')),huds:[...root.querySelectorAll('.dfy-active-hud')].filter(n=>!n.hidden).map(r),sprites:[b.nearSide,b.farSide].flatMap(s=>s.active.filter(Boolean).map(p=>({name:p.speciesForme,...r(p.sprite.$el[0])}))),commands:r(root.querySelector('.dfy-game-buttons')),switches:[...root.querySelectorAll('.dfy-switch-strip .dfy-game-action')].map(r),moveCount:root.querySelectorAll('.dfy-game-command [data-native-action=chooseMove]').length,bodyWidth:document.body.scrollWidth,screenWidth:innerWidth}})()`);
    if(geometry.fixtureError)throw Error(geometry.fixtureError);assert.equal(geometry.huds.length,doubles?4:2);assert.equal(geometry.moveCount,4);assert(geometry.bodyWidth<=geometry.screenWidth+1);
    const intersects=(a,b)=>a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y;
    for(const [i,hud]of geometry.huds.entries()){assert(hud.x>=geometry.arena.x-1&&hud.right<=geometry.arena.right+1&&hud.y>=geometry.arena.y-1&&hud.bottom<=geometry.arena.bottom+1);assert(!geometry.huds.slice(i+1).some(other=>intersects(hud,other)),'HUD overlap');}
    for(const sprite of geometry.sprites){assert(sprite.x>=geometry.arena.x-1&&sprite.right<=geometry.arena.right+1&&sprite.y>=geometry.arena.y-1&&sprite.bottom<=geometry.arena.bottom+1,JSON.stringify({id,w,sprite,arena:geometry.arena}));assert(Math.max(sprite.w,sprite.h)>geometry.arena.h*.2,'Pokemon too small');assert(!geometry.huds.some(hud=>intersects(sprite,hud)),'Pokemon intersects HP card '+JSON.stringify({id,w,sprite}));}
    if(h===720)for(const card of geometry.switches)assert(card.bottom<=geometry.commands.bottom+2,'Compact window clips switch card '+JSON.stringify({id,card,commands:geometry.commands}));
    report.push({mode:id,size:[w,h],...geometry});
   }
  }
  const effects=['|-weather|RainDance','|-fieldstart|move: Trick Room','|-fieldstart|move: Grassy Terrain','|-sidestart|p1: 布局甲|Tailwind','|-sidestart|p1: 布局甲|Reflect','|-sidestart|p2: 布局乙|Light Screen','|-boost|p1a: Rotom-Wash|spa|2'];
  for(const id of ['66','64','63']){room='battle-gen9ou-locallayout'+id;await run(`app.focusRoom('${room}')`);await receive(effects);await until(`app.rooms['${room}'].battle.atQueueEnd`);await sleep(550);await capture('layout-'+id+'-field-1100');const check=await run(`(()=>{const root=document.getElementById('room-${room}'),arena=root.querySelector('.dfy-game-arena').getBoundingClientRect();return {icons:root.querySelectorAll('.dfy-effect-icon').length,fit:[...root.querySelectorAll('.dfy-active-hud')].filter(n=>!n.hidden).every(n=>{const r=n.getBoundingClientRect();return r.y>=arena.y&&r.bottom<=arena.bottom})}})()`);assert(check.icons>=6&&check.fit,JSON.stringify(check));
   await receive(['|move|p1a: Rotom-Wash|Thunderbolt|p2a: Kyogre','|-supereffective|p2a: Kyogre','|-crit|p2a: Kyogre','|-damage|p2a: Kyogre|30/100','|turn|2']);await until(`!!document.getElementById('room-${room}').querySelector('.dfy-impact-title[data-kind=critical]')`);assert.equal(await run(`document.getElementById('room-${room}').querySelectorAll('.dfy-impact-title').length`),1,'One combined impact caption');await capture('layout-'+id+'-critical-1100');await until(`app.rooms['${room}'].battle.atQueueEnd`);
  }
  for(const id of ['66','64','63']){room='battle-gen9ou-locallayout'+id;await run(`app.focusRoom('${room}')`);await receive(['|switch|p1a: Incineroar|Incineroar, L50|200/200','|switch|p2a: Groudon|Groudon, L50|100/100',...(id==='64'?['|switch|p2b: Rayquaza|Rayquaza, L50|100/100']:[]),'|turn|3']);await until(`app.rooms['${room}'].battle.atQueueEnd`);for(const [w,h]of [[1440,960],[1100,720]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[w,h]);await sleep(550);await capture('layout-'+id+'-large-'+w);const check=await run(`(()=>{const root=document.getElementById('room-${room}'),a=root.querySelector('.dfy-game-arena').getBoundingClientRect(),huds=[...root.querySelectorAll('.dfy-active-hud')].filter(n=>!n.hidden).map(n=>n.getBoundingClientRect()),b=app.rooms['${room}'].battle;return [b.nearSide,b.farSide].flatMap(s=>s.active.filter(Boolean)).map(p=>{const r=p.sprite.$el[0].getBoundingClientRect();return {name:p.speciesForme,inside:r.x>=a.x&&r.right<=a.right&&r.y>=a.y&&r.bottom<=a.bottom,clear:huds.every(h=>!(r.x<h.right&&r.right>h.x&&r.y<h.bottom&&r.bottom>h.y))}})})()`);assert(check.every(p=>p.inside&&p.clear),'Large Pokemon clip/overlap '+JSON.stringify({id,w,check}));}}
  fs.writeFileSync(out+'/layout-matrix.json',JSON.stringify(report,null,2));console.log({cases:report.length,modes:['66','64','63'],navigation:'desktop accounts',screenshots:out});
 }catch(error){fs.writeFileSync(out+'/layout-failure.json',JSON.stringify({host:await page.evaluate(()=>({visibility:document.visibilityState,active:document.querySelector('[data-page][aria-current=true]')?.outerHTML,rect:document.querySelector('#showdown-container')?.getBoundingClientRect(),body:document.body.outerHTML.slice(0,9000)})),windows:await app.evaluate(({BrowserWindow,webContents})=>({windows:BrowserWindow.getAllWindows().map(w=>({title:w.getTitle(),visible:w.isVisible(),bounds:w.getBounds(),children:w.contentView.children.map(v=>({bounds:v.getBounds(),url:v.webContents?.getURL()}))})),contents:webContents.getAllWebContents().map(w=>({id:w.id,url:w.getURL()}))})),game:await run('({state:document.visibilityState,w:innerWidth,h:innerHeight,arena:document.querySelector(".dfy-game-arena")?.getBoundingClientRect()})')},null,2));await page.screenshot({path:out+'/layout-host-failure.png'});throw error;}finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
