'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),crypto=require('crypto');
const {_electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const out=process.env.SHOWDOWN_TEST_OUTPUT||path.resolve('test-results/0.5.7');fs.mkdirSync(out,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const env={...process.env,DFY_PLAY_HOME:out+'/battle-data',DFY_PLAY_CACHE:out+'/battle-cache'};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:process.env.SHOWDOWN_TEST_EXE||path.resolve('node_modules/electron/dist/electron.exe'),args:process.env.SHOWDOWN_TEST_EXE?[]:[path.resolve('.')],env});await app.firstWindow();
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.restore();w.show();w.focus();});
 const run=code=>app.evaluate(async({webContents},code)=>{const w=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com'));if(w)w.setBackgroundThrottling(false);return w?.executeJavaScript(code);},code);
 const shot=async(name,clip)=>{const base64=await app.evaluate(async({webContents},clip)=>(await webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com')).capturePage(clip)).toPNG().toString('base64'),clip);const bytes=Buffer.from(base64,'base64');fs.writeFileSync(out+'/'+name+'.png',bytes);return crypto.createHash('sha256').update(bytes).digest('hex');};
 const until=async(code)=>{for(let i=0;i<120;i++){if(await run(code))return;await sleep(250);}throw Error('Timed out: '+code);};
 const room='battle-gen9ou-localacceptance';const receive=lines=>run('app.receive('+JSON.stringify('>'+room+'\n'+lines.join('\n'))+')');const checks=[];
 try{
  await until('!!(window.app&&window.__dfyGame&&window.__dfyLobby&&window.Battle&&window.TeamPopup)');
  // No match, chat, or choice is sent to the public server during this fixture.
  await run(`window.__testSent=[];app.send=(...args)=>window.__testSent.push(args);Storage.teams=[{name:'伽勒尔测试队',format:'gen9ou',team:Storage.packTeam([{species:'Slowking-Galar',ability:'Regenerator',moves:['Future Sight']},{species:'Great Tusk',ability:'Protosynthesis',moves:['Close Combat']}])},{name:'双属性测试队',format:'gen9ou',team:Storage.packTeam([{species:'Venusaur',ability:'Chlorophyll',moves:['Giga Drain']}])}];app.rooms[''].curTeamIndex=0;app.rooms[''].curFormat='gen9ou';app.rooms[''].updateFormats();app.rooms[''].el.querySelector('button[name=format]').value='gen9ou';app.rooms[''].updateTeams();const nativeTeam=app.rooms[''].el.querySelector('button[name=team]');nativeTeam.disabled=false;nativeTeam.classList.remove('disabled');nativeTeam.value='0';nativeTeam.innerHTML=TeamPopup.renderTeam(0);app.focusRoom('');`);
  await until(`!!document.querySelector('.dfy-game-hub [data-native-action=team] .dfy-team-miniatures img')`);
  await run(`document.querySelector('.dfy-game-hub [data-native-action=team]').click()`);
  await until(`!!document.querySelector('.dfy-team-popup [name=selectTeam][value="1"]')`);
  assert.equal(await run(`document.querySelectorAll('.dfy-team-popup [name=selectTeam][value="0"] img').length`),2);await shot('team-picker');
  await run(`document.querySelector('.dfy-team-popup [name=selectTeam][value="1"]').click()`);await until(`app.rooms[''].curTeamIndex===1&&!document.querySelector('.dfy-team-popup')`);checks.push('mouse team selection updates native selected team and local sprite cards');
  await receive(['|init|battle','|title|对战呈现验收','|gametype|singles','|gen|9','|tier|[Gen 9] OU','|player|p1|本地甲|1','|player|p2|本地乙|2','|teamsize|p1|6','|teamsize|p2|6',...['Kingambit','Slowking-Galar','Great Tusk','Gholdengo','Dragonite','Ogerpon-Wellspring'].map(n=>'|poke|p1|'+n),...['Great Tusk','Venusaur','Zamazenta','Gholdengo','Dragonite','Iron Valiant'].map(n=>'|poke|p2|'+n),'|teampreview']);
  await run(`app.focusRoom('${room}')`);await until(`document.querySelector('.dfy-game-arena')?.dataset.preview==='true'`);await sleep(200);await shot('battle-preview');
  assert.equal(await run(`getComputedStyle(document.querySelector('.dfy-game-arena>.battle')).visibility`),'hidden');assert.equal(await run(`document.querySelectorAll('.dfy-preview-row img').length`),6);checks.push('own-only preview and opponent sidebar; no native sprites behind it');
  await receive(['|start','|switch|p1a: Kingambit|Kingambit, M|341/341','|switch|p2a: Great Tusk|Great Tusk|100/100','|turn|1']);
  await until(`!!document.querySelector('.dfy-entry-title')`);await shot('battle-entry');await sleep(3500);
  const geometry=await run(`(()=>{const b=app.rooms['${room}'].battle;return b.sides.map(s=>s.active.filter(Boolean).map(p=>({name:p.speciesForme,width:parseFloat(p.sprite.$el[0].style.width),height:parseFloat(p.sprite.$el[0].style.height),top:parseFloat(p.sprite.$el[0].style.top),url:p.sprite.$el[0].src}))[0])})()`);
  for(const p of geometry)assert(p.height<220&&p.width<220&&p.top+p.height<=340,JSON.stringify(p));assert(geometry[0].height>geometry[1].height);checks.push('near/far sizes include native perspective once and stay grounded inside arena');
  const clip=await run(`(()=>{const r=app.rooms['${room}'].battle.nearSide.active[0].sprite.$el[0].getBoundingClientRect();return{x:Math.floor(r.x),y:Math.floor(r.y),width:Math.ceil(r.width),height:Math.ceil(r.height)}})()`);
  const frameA=await shot('idle-frame-a',clip);await sleep(310);const frameB=await shot('idle-frame-b',clip);assert.notEqual(frameA,frameB);checks.push('actual local animated sprite changes rendered frames while idle');
  await receive(['|move|p2a: Great Tusk|Close Combat|p1a: Kingambit','|-supereffective|p1a: Kingambit','|-crit|p1a: Kingambit','|-damage|p1a: Kingambit|15/341','|upkeep','|turn|2']);
  await until(`!!document.querySelector('.dfy-impact-title[data-kind=critical]')`);await shot('battle-critical');await sleep(2500);
  const request={rqid:1,active:[{moves:[{move:'Swords Dance',id:'swordsdance',pp:32,maxpp:32,target:'self',disabled:false},{move:'Sucker Punch',id:'suckerpunch',pp:8,maxpp:8,target:'normal',disabled:false},{move:'Kowtow Cleave',id:'kowtowcleave',pp:16,maxpp:16,target:'normal',disabled:false},{move:'Iron Head',id:'ironhead',pp:24,maxpp:24,target:'normal',disabled:false}],canTerastallize:'Ghost'}],side:{name:'本地甲',id:'p1',pokemon:['Kingambit','Slowking-Galar','Great Tusk','Gholdengo','Dragonite','Ogerpon-Wellspring'].map((n,i)=>({ident:'p1: '+n,details:n+', L100',condition:i?'300/300':'15/341',active:i===0,stats:{atk:300,def:220,spa:150,spd:220,spe:180},moves:i?['tackle']:['swordsdance','suckerpunch','kowtowcleave','ironhead'],baseAbility:i?'':'supremeoverlord',item:'',teraType:i?'Water':'Ghost'}))}};
  await receive(['|request|'+JSON.stringify(request)]);await until(`document.querySelectorAll('.dfy-game-command [data-native-action=chooseMove]').length===4`);await shot('battle-ready');checks.push('native four move commands and six switch cards remain available');
  await receive(Array.from({length:40},(_,i)=>'|message|回放记录 '+(i+1)));await sleep(400);
  await run(`const n=document.querySelector('.dfy-game-record .battle-log');n.scrollTop=0;n.dispatchEvent(new Event('scroll'));`);assert.equal(await run(`document.querySelector('.dfy-log-follow').getAttribute('aria-pressed')`),'false');
  await receive(['|message|新的回合信息']);await sleep(350);assert(await run(`document.querySelector('.dfy-game-record .battle-log').scrollTop<20`));
  await run(`document.querySelector('.dfy-log-follow').click()`);assert(await run(`(()=>{const n=document.querySelector('.dfy-game-record .battle-log');return n.scrollHeight-n.clientHeight-n.scrollTop<30})()`));checks.push('scrolling history stays put when events arrive; return to latest works');
  const audio=await run(`window.__dfyBattleAudio.music`);assert.match(audio.track,/bgm\/battle-(galar|paldea)-/);assert(audio.readyState>=2&&!audio.paused);await run(`window.__dfyBattleAudio.setVolume(.35)`);assert.equal(await run(`window.__dfyBattleAudio.music.master`),.35);checks.push('Sword Shield or Scarlet Violet local BGM plays and volume responds');
  const evidence=await run('window.__dfyGame.evidence()'),events=evidence.find(e=>e.room===room).events;for(const k of ['entry-fx','battle-entry','move-accent','impact-fx'])assert(events.some(e=>e.kind===k),k);for(const k of ['critical','super4'])assert(events.some(e=>e.kind==='impact-sound'&&e.name===k));
  await receive(['|-weather|RainDance','|-fieldstart|move: Trick Room','|-fieldstart|move: Electric Terrain','|-sidestart|p1: 本地甲|Tailwind','|-sidestart|p2: 本地乙|Tailwind','|-sidestart|p1: 本地甲|Stealth Rock','|-sidestart|p2: 本地乙|Reflect','|-sidestart|p2: 本地乙|Light Screen','|-boost|p1a: Kingambit|atk|2','|-unboost|p2a: Great Tusk|def|1']);
  await until(`document.querySelectorAll('.dfy-effect-icon').length>=8&&document.querySelector('.dfy-active-hud[data-side=near] .dfy-boost-summary').textContent.includes('+2')`);
  assert.equal(await run(`document.querySelectorAll('.dfy-field-inspect').length`),0);
  assert(await run(`document.querySelector('.dfy-active-hud[data-side=far] [data-effect=reflect]')&&document.querySelector('.dfy-active-hud[data-side=near] [data-effect=stealthrock]')`));await until(`app.rooms['${room}'].battle.atQueueEnd`);await sleep(600);await shot('field-rain-space');fs.writeFileSync(out+'/stage-dom.json',JSON.stringify(await run(`({html:document.querySelector('.dfy-game-arena').innerHTML,bgs:[...document.querySelectorAll('.battle,.battle *')].filter(n=>{const c=getComputedStyle(n);return c.display!=='none'&&(c.backgroundColor!=='rgba(0, 0, 0, 0)'||c.backgroundImage!=='none')}).map(n=>({cls:n.className,bg:getComputedStyle(n).background,rect:{width:n.clientWidth,height:n.clientHeight}}))})`),null,2));
  // Send real Electron mouse movement; a programmatic click alone would miss hover hitbox bugs.
  const hover=async selector=>{const pos=await run(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);await app.evaluate(({webContents},pos)=>webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com')).sendInputEvent({type:'mouseMove',...pos}),pos);};
  await hover('.dfy-active-hud[data-side=near] [data-effect=stealthrock]');await sleep(450);assert(!await run(`!!document.querySelector('.dfy-field-panel:popover-open')`));await hover('.dfy-active-hud[data-side=near] .dfy-hp-track');await until(`document.querySelector('.dfy-field-panel:popover-open')?.textContent.includes('隐形岩')`);await shot('field-hazard-tooltip');
  await hover('.dfy-active-hud[data-side=far] .dfy-hp-track');await until(`document.querySelector('.dfy-field-panel:popover-open')?.textContent.includes('已公开招式')`);assert(await run(`document.querySelector('.dfy-field-panel').textContent.includes('尚未公开')`));assert(await run(`document.querySelector('.dfy-field-panel').textContent.includes('近身战')`));await shot('opponent-known-info');
  await hover('.dfy-active-hud[data-side=near] .dfy-hp-track');await until(`document.querySelector('.dfy-field-panel:popover-open')?.textContent.includes('+2')`);assert(await run(`document.querySelector('.dfy-field-panel').textContent.includes('×2')`));await shot('boost-tooltip');
  await run(`document.querySelector('.dfy-panel-close').click()`);checks.push('fixed weather and side icons, real mouse hover tooltips, known opponent data and boost multipliers');
  const fieldProbe=async()=>{const value=await run(`({image:document.querySelector('.dfy-field-air').toDataURL(),field:window.__dfyGame.evidence().find(e=>e.room==='${room}').field,hidden:document.hidden,paused:app.rooms['${room}'].battle.paused,seeking:app.rooms['${room}'].battle.seeking,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches})`);return {...value,image:crypto.createHash('sha256').update(value.image).digest('hex')};};
  const fieldBefore=await fieldProbe();await sleep(300);const fieldAfter=await fieldProbe();fs.writeFileSync(out+'/field-animation.json',JSON.stringify({before:fieldBefore,after:fieldAfter},null,2));assert.notEqual(fieldAfter.image,fieldBefore.image,'Visible weather animation must render different frames: '+JSON.stringify({before:fieldBefore,after:fieldAfter}));
  await receive(['|-sideend|p1: 本地甲|Tailwind','|-fieldend|move: Trick Room','|-fieldend|move: Electric Terrain','|-weather|SunnyDay']);await until(`document.querySelector('.dfy-game-arena').dataset.weather==='sunnyday'&&!document.querySelector('.dfy-effect-icon[data-effect=trickroom]')`);assert(await run(`!document.querySelector('.dfy-active-hud[data-side=near] [data-effect=tailwind]')&&!!document.querySelector('.dfy-active-hud[data-side=far] [data-effect=tailwind]')`));await shot('field-sun');
  for(const weather of ['Sandstorm','Snowscape','Hail','PrimordialSea','DesolateLand','DeltaStream']){await receive(['|-weather|'+weather]);await until(`document.querySelector('.dfy-game-arena').dataset.weather==='${weather.toLowerCase()}'`);}
  for(const terrain of ['Grassy Terrain','Misty Terrain','Psychic Terrain']){await receive(['|-fieldstart|move: '+terrain]);await until(`document.querySelector('.dfy-game-arena').dataset.terrain==='${terrain.toLowerCase().replaceAll(' ','')}'`);}
  await receive(['|-fieldstart|move: Magic Room','|-fieldstart|move: Wonder Room','|-fieldstart|move: Gravity']);await until(`document.querySelector('.dfy-game-arena').dataset.rooms.includes('gravity')`);await shot('field-gravity-terrain');
  await receive(['|-weather|none','|-fieldend|move: Psychic Terrain','|-fieldend|move: Magic Room','|-fieldend|move: Wonder Room','|-fieldend|move: Gravity','|-sideend|p1: 本地甲|Stealth Rock','|-sideend|p2: 本地乙|Tailwind','|-sideend|p2: 本地乙|Reflect','|-sideend|p2: 本地乙|Light Screen','|-clearallboost']);await until(`document.querySelectorAll('.dfy-effect-icon').length===0&&document.querySelector('.dfy-active-hud[data-side=near] .dfy-boost-summary').textContent===''`);assert.equal(await run(`document.querySelector('.dfy-active-hud[data-side=near] .dfy-boost-summary').textContent`),'');checks.push('animated weather, all four terrains, rooms, independent side effects and end events clear without stale visuals');
  // Existing stage stays readable during offline playbacks and page navigation.
  await app.evaluate(async({webContents})=>{const w=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com'));await w.session.enableNetworkEmulation({offline:true});});
  assert(await run(`fetch('dfy-asset://battle/sprite/slowkinggalar/front/normal/M').then(r=>r.ok)`));await run(`app.focusRoom('');app.focusRoom('${room}')`);await sleep(400);assert(await run(`!!document.querySelector('.dfy-game-arena').getClientRects().length`));checks.push('offline form assets and navigation remain responsive');
  fs.writeFileSync(out+'/battle-acceptance.json',JSON.stringify({checks,geometry,audio,evidence},null,2));console.log(JSON.stringify({checks,geometry,audio},null,2));
 }catch(error){fs.writeFileSync(out+'/battle-failure.json',JSON.stringify(await run(`({hover:[...document.querySelectorAll(':hover')].map(n=>n.className),panel:document.querySelector('.dfy-field-panel')?.outerHTML,hps:[...document.querySelectorAll('.dfy-hp-track')].map(n=>({html:n.outerHTML,rect:JSON.stringify(n.getBoundingClientRect()),pointer:getComputedStyle(n).pointerEvents})),teams:Storage.teams,home:app.rooms[''].curTeamIndex,popups:[...document.querySelectorAll('.ps-popup')].map(e=>e.outerHTML),buttons:document.querySelector('.dfy-game-hub')?.outerHTML})`),null,2));throw error;}finally{await app.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
