'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {_electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const out=process.env.SHOWDOWN_TEST_OUTPUT||path.resolve('test-results/0.5.7'),sleep=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(out,{recursive:true});
(async()=>{const env={...process.env,DFY_PLAY_HOME:out+'/doubles-data',DFY_PLAY_CACHE:out+'/doubles-cache'};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:process.env.SHOWDOWN_TEST_EXE||path.resolve('node_modules/electron/dist/electron.exe'),args:process.env.SHOWDOWN_TEST_EXE?[]:[path.resolve('.')],env});await app.firstWindow();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());
 const run=code=>app.evaluate(async({webContents},code)=>{const w=webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com'));w?.setBackgroundThrottling(false);return w?.executeJavaScript(code);},code.replaceAll('document.querySelector(',"document.getElementById('room-"+room+"').querySelector(").replaceAll('document.querySelectorAll(',"document.getElementById('room-"+room+"').querySelectorAll("));
 const until=async code=>{for(let i=0;i<120;i++){if(await run(code))return;await sleep(250);}throw Error('Timed out: '+code);};
 const shot=async name=>{const b64=await app.evaluate(async({webContents})=>(await webContents.getAllWebContents().find(w=>w.getURL().startsWith('https://play.pokemonshowdown.com')).capturePage()).toPNG().toString('base64'));fs.writeFileSync(out+'/'+name+'.png',Buffer.from(b64,'base64'));};
 const room='battle-gen9vgc2025regi-doublescheck',receive=lines=>run('app.receive('+JSON.stringify('>'+room+'\n'+lines.join('\n'))+')');const checks=[];
 const team=['Rotom-Wash','Gholdengo','Incineroar','Rillaboom','Urshifu-Rapid-Strike','Calyrex-Ice'],foe=['Kyogre','Tornadus','Amoonguss','Incineroar','Rillaboom','Miraidon'];
 const mons=(list,active=false)=>list.map((n,i)=>({ident:'p1: '+n,details:n+', L50',condition:'200/200',active:active&&i<2,stats:{atk:120,def:130,spa:170,spd:145,spe:140},moves:['thunderbolt','hydropump','protect','voltswitch'],baseAbility:i?'goodasgold':'levitate',item:'',teraType:'Grass'}));
 const nativeButtons=()=>run(`([...document.querySelectorAll('#room-${room} .battle-controls button')].map(n=>({name:n.name,value:n.value,text:n.textContent,disabled:n.disabled})))`);
 try{
  await until('!!(window.app&&window.__dfyGame&&window.Battle)');await run(`window.__testSent=[];app.send=(...args)=>window.__testSent.push(args);true;`);
  await receive(['|init|battle','|title|6 选 4 双打验收','|gametype|doubles','|gen|9','|tier|[Gen 9] VGC 2025 Reg I','|player|p1|双打甲|1','|player|p2|双打乙|2','|teamsize|p1|6','|teamsize|p2|6',...team.map(n=>'|poke|p1|'+n+', L50'),...foe.map(n=>'|poke|p2|'+n+', L50'),'|teampreview|4','|request|'+JSON.stringify({rqid:1,teamPreview:true,maxTeamSize:4,side:{name:'双打甲',id:'p1',pokemon:mons(team)}})]);
  await run(`app.focusRoom('${room}')`);await sleep(400);await receive(['|request|'+JSON.stringify({rqid:1,teamPreview:true,maxTeamSize:4,side:{name:'双打甲',id:'p1',pokemon:mons(team)}})]);await until(`document.querySelectorAll('.dfy-team-preview [data-preview-pokemon]').length===6`);fs.writeFileSync(out+'/doubles-client-probe.json',JSON.stringify(await run(`({choice:Object.fromEntries(Object.entries(app.rooms['${room}'].choice||{}).filter(([k,v])=>v===null||['number','string','boolean'].includes(typeof v))),chooseTeam:app.rooms['${room}'].chooseTeamPreview.toString(),updateTeam:app.rooms['${room}'].updateTeamControls?.toString(),chooseMove:app.rooms['${room}'].chooseMove.toString(),chooseTarget:app.rooms['${room}'].chooseMoveTarget.toString(),endTurn:app.rooms['${room}'].endTurn.toString(),clearChoice:app.rooms['${room}'].clearChoice.toString(),endChoice:app.rooms['${room}'].endChoice.toString()})`),null,2));await shot('doubles-preview');fs.writeFileSync(out+'/doubles-preview-buttons.json',JSON.stringify(await nativeButtons(),null,2));
  assert.equal(await run("document.querySelectorAll('.dfy-team-preview .dfy-preview-team').length"),1);
  const selectedColor=await run("getComputedStyle(document.querySelector('[data-order-slot=\"0\"]')).backgroundColor");assert.notEqual(selectedColor,await run("getComputedStyle(document.querySelector('[data-order-slot=\"1\"]')).backgroundColor"),'active position must be visibly highlighted');
  for(const [slot,mon]of [[2,4],[0,0],[1,1],[3,3]]){await run(`document.querySelector('[data-order-slot="${slot}"]').click();document.querySelector('.dfy-team-preview [data-preview-pokemon="${mon}"]').click();true;`);await sleep(130);}
  assert(!(await run('window.__testSent')).some(a=>a.some(v=>String(v).includes('/team '))));
  await shot('doubles-preview-selected');assert.equal(await run("getComputedStyle(document.querySelector('[data-choice-action=confirm]')).backgroundColor"),'rgb(213, 92, 117)');
  await run(`document.querySelector('[data-order-slot="2"]').click();document.querySelector('[data-choice-action=clear]').click();true;`);assert(await run("document.querySelector('[data-choice-action=confirm]').disabled"));
  await run(`document.querySelector('.dfy-team-preview [data-preview-pokemon="4"]').click();document.querySelector('[data-choice-action=confirm]').click();true;`);await sleep(200);
  const sent=await run('window.__testSent');assert(sent.some(args=>args.some(v=>String(v).includes('/team 125436'))),JSON.stringify(sent));checks.push('own-only preview; arbitrary position buttons, undo and explicit confirmation; opponent stays in sidebar');
  await receive(['|start','|switch|p1a: Rotom-Wash|Rotom-Wash, L50|200/200','|switch|p1b: Gholdengo|Gholdengo, L50|200/200','|switch|p2a: Kyogre|Kyogre, L50|100/100','|switch|p2b: Tornadus|Tornadus, L50|100/100','|turn|1']);await sleep(4000);
  const move=(name,id,target)=>({move:name,id,pp:16,maxpp:16,target,disabled:false});const request={rqid:2,active:[{moves:[move('Thunderbolt','thunderbolt','normal'),move('Hydro Pump','hydropump','normal'),move('Protect','protect','self'),move('Volt Switch','voltswitch','normal')],canTerastallize:'Grass'},{moves:[move('Shadow Ball','shadowball','normal'),move('Make It Rain','makeitrain','allAdjacentFoes'),move('Protect','protect','self'),move('Nasty Plot','nastyplot','self')],canTerastallize:'Steel'}],side:{name:'双打甲',id:'p1',pokemon:mons(team.slice(0,4),true)}};
  await receive(['|request|'+JSON.stringify(request)]);await until(`document.querySelectorAll('.dfy-game-command [data-native-action=chooseMove]').length===4`);await shot('doubles-ready');
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="1"]').click()`);await until(`document.querySelectorAll('.dfy-game-command [data-native-action=chooseMoveTarget]').length>0`);await shot('doubles-targets');fs.writeFileSync(out+'/doubles-target-buttons.json',JSON.stringify(await nativeButtons(),null,2));
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMoveTarget][data-native-value="1"]').click()`);await until(`document.querySelector('.dfy-game-command [data-native-action=chooseMove]')?.textContent.includes('暗影球')`);await shot('doubles-second-action');
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="3"]').click()`);await until(`!document.querySelector('.dfy-custom-choice').hidden`);assert(!(await run('window.__testSent')).some(a=>a.some(v=>String(v).includes('/choose '))));await run(`document.querySelector('[data-choice-action=confirm]').click();true;`);await until(`window.__testSent.some(a=>a.some(v=>String(v).includes('/choose ')))`);checks.push('first Pokemon picks target, second Pokemon receives independent move set and both commands submit');
  await receive(['|request|'+JSON.stringify({...request,rqid:3})]);await until(`document.querySelectorAll('.dfy-game-command [data-native-action=chooseMove]').length===4`);
  await receive(['|-sidestart|p1: 双打甲|Tailwind','|-sidestart|p1: 双打甲|Reflect','|-sidestart|p2: 双打乙|Stealth Rock','|-boost|p1b: Gholdengo|spa|2']);await until(`app.rooms['${room}'].battle.atQueueEnd`);await sleep(600);
  for(const [w,h]of [[1440,960],[1100,720]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),[w,h]);await sleep(600);await shot('doubles-'+w+'x'+h);const data=await run(`(()=>{const r=n=>{const x=n.getBoundingClientRect();return{x:x.x,y:x.y,w:x.width,h:x.height,right:x.right,bottom:x.bottom}};return{arena:r(document.querySelector('.dfy-game-arena')),huds:[...document.querySelectorAll('.dfy-active-hud')].filter(n=>!n.hidden).map(n=>({side:n.dataset.side,slot:n.dataset.slot,...r(n)})),command:r(document.querySelector('.dfy-game-command')),bodyWidth:document.body.scrollWidth,screenWidth:innerWidth}})()`);fs.writeFileSync(out+'/doubles-layout-'+w+'.json',JSON.stringify(data,null,2));assert.equal(data.huds.length,4);for(const a of data.huds){assert(a.x>=data.arena.x-1&&a.right<=data.arena.right+1&&a.y>=data.arena.y-1&&a.bottom<=data.arena.bottom+1,JSON.stringify(a));for(const b of data.huds){if(a===b)continue;assert(!(a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y),'HUD overlap '+JSON.stringify([a,b]));}}assert(data.bodyWidth<=data.screenWidth+1);}

  fs.writeFileSync(out+'/doubles-ground.png',Buffer.from((await run("document.querySelector('.dfy-field-ground').toDataURL('image/png')")).split(',')[1],'base64'));
  await receive(['|swap|p1a: Rotom-Wash|1|[from] move: Ally Switch']);await until(`app.rooms['${room}'].battle.atQueueEnd`);assert.equal(await run(`app.rooms['${room}'].battle.nearSide.active[1].speciesForme`),'Rotom-Wash');await sleep(250);await shot('doubles-swapped');await receive(['|swap|p1b: Rotom-Wash|0|[from] move: Ally Switch']);await until(`app.rooms['${room}'].battle.atQueueEnd`);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,960));
  const special={...request,rqid:4,active:[{moves:[move('Earthquake','earthquake','allAdjacent'),move('Helping Hand','helpinghand','adjacentAlly'),move('Ally Switch','allyswitch','self'),move('Protect','protect','self')]},request.active[1]]};
  await receive(['|request|'+JSON.stringify(special)]);await until(`document.querySelector('.dfy-game-command [data-native-value="1"] .dfy-move-scope')?.textContent.includes('含队友')`);
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="1"]').click()`);await until(`document.querySelector('.dfy-game-command [data-native-action=chooseMove]')?.textContent.includes('暗影球')`);assert.equal(await run("document.querySelectorAll('.dfy-game-command [data-native-action=chooseMoveTarget]').length"),0);
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="2"]').click()`);await until("!!document.querySelector('[data-edit-slot=\"1\"]')");await shot('doubles-confirm');
  await run(`document.querySelector('[data-edit-slot="1"]').click()`);await until(`document.querySelector('.dfy-game-command [data-native-action=chooseMove]')?.textContent.includes('暗影球')`);await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="3"]').click();document.querySelector('[data-choice-action=confirm]').click();true;`);await sleep(150);
  await receive(['|request|'+JSON.stringify({...special,rqid:5})]);await sleep(200);await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="2"]').click()`);await until(`!!document.querySelector('.dfy-game-command [data-native-action=chooseMoveTarget][data-native-value="-2"]')`);const targets=await run(`[...document.querySelectorAll('.dfy-game-command [data-native-action=chooseMoveTarget]:not(:disabled)')].map(b=>b.dataset.nativeValue)`);assert.deepEqual(targets,['-2']);await shot('doubles-helping-hand');
  await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMoveTarget][data-native-value="-2"]').click();true;`);await sleep(120);await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="3"]').click();document.querySelector('[data-choice-action=confirm]').click();true;`);await sleep(200);
  assert((await run('window.__testSent')).some(a=>a.some(v=>String(v).includes('move 2 -2'))));
  await receive(['|request|'+JSON.stringify({...special,rqid:6})]);await sleep(200);await run(`document.querySelector('.dfy-game-command [data-native-action=chooseMove][data-native-value="3"]').click()`);await until(`document.querySelector('.dfy-game-command [data-native-action=chooseMove]')?.textContent.includes('暗影球')`);assert.equal(await run("document.querySelectorAll('.dfy-game-command [data-native-action=chooseMoveTarget]').length"),0);
  await receive(['|-ability|p2a: Kyogre|Drizzle','|-weather|RainDance|[from] ability: Drizzle|[of] p2a: Kyogre','|-ability|p1b: Gholdengo|Drought','|-weather|SunnyDay|[from] ability: Drought|[of] p1b: Gholdengo','|-fieldstart|move: Electric Terrain','|-fieldstart|move: Grassy Terrain']);await until(`app.rooms['${room}'].battle.atQueueEnd`);await sleep(400);assert.equal(await run("document.querySelectorAll('.dfy-effect-icon[data-effect=raindance],.dfy-effect-icon[data-effect=electricterrain]').length"),0);assert.equal(await run("document.querySelectorAll('.dfy-effect-icon[data-effect=sunnyday],.dfy-effect-icon[data-effect=grassyterrain]').length"),2);assert(await run("document.querySelectorAll('.dfy-ability-toast').length<=1"));
  const sizes=await run(`(()=>{const b=app.rooms['${room}'].battle;return b.farSide.active.map(p=>({name:p.speciesForme,w:p.sprite.$el[0].width,h:p.sprite.$el[0].height}))})()`);assert(sizes[0].w>sizes[1].w*1.5,JSON.stringify(sizes));fs.writeFileSync(out+'/doubles-sizes.json',JSON.stringify(sizes,null,2));
  await shot('doubles-weather-overwrite');
  fs.writeFileSync(out+'/doubles-styles.json',JSON.stringify(await run(`[...document.querySelectorAll('.dfy-game-arena,.battle,.innerbattle,.battle>*,.innerbattle>*')].map(n=>({cls:n.className,style:n.getAttribute('style'),bg:getComputedStyle(n).background,filter:getComputedStyle(n).filter,box:getComputedStyle(n).boxShadow,before:getComputedStyle(n,'::before').cssText,after:getComputedStyle(n,'::after').background}))`),null,2));
  checks.push('spread moves label allied damage, Helping Hand targets ally, Ally Switch needs no target, actions editable until confirmation, later weather/terrain replace earlier state, Kyogre visually exceeds Tornadus');
  checks.push('four HUDs stay inside arena and do not overlap at 1440x960 and 1100x720');fs.writeFileSync(out+'/doubles-acceptance.json',JSON.stringify({checks,sent:await run('window.__testSent')},null,2));console.log(checks);
 }catch(error){await shot('doubles-failure');fs.writeFileSync(out+'/doubles-failure.json',JSON.stringify({error:error.message,buttons:await nativeButtons(),data:await run(`JSON.stringify({controls:app.rooms['${room}']?.el.querySelector('.battle-controls')?.innerHTML,sent:window.__testSent})`)},null,2));throw error;}finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
