'use strict';
const fixture=require('./electron-fixture.cjs');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{_electron}=require('playwright');
const out=process.env.SHOWDOWN_TEST_OUTPUT||path.resolve('test-results/generation');fs.mkdirSync(out,{recursive:true});
(async()=>{const env={...process.env,DFY_PLAY_HOME:out+'/starter-data',DFY_PLAY_CACHE:out+'/starter-cache'};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:path.resolve('node_modules/electron/dist/electron.exe'),args:[...fixture.flags,path.resolve('.')],env}),page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);const shot=async name=>{const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG().toString('base64'));fs.writeFileSync(out+'/'+name+'.png',Buffer.from(png,'base64'));};
 try{await fixture.isolate(app);await page.click('[data-page=teams]');await page.waitForSelector('#team-format-button');
  const choose=async id=>{await page.click('#team-format-button');await page.locator('.dfy-format-picker>input').fill(id);const option=page.locator('.dfy-format-options [data-rule-format="'+id+'"]');await page.mouse.move(4,4);await option.hover();await page.waitForSelector('.dfy-rule-tip:popover-open');const text=await page.locator('.dfy-rule-tip').textContent();await option.click();await page.waitForFunction(id=>window.__playState.teamEditorData?.format===id,id);return text;};
  const create=async()=>{await page.locator('.page-head [data-action=team-new]').click();await page.waitForFunction(()=>!__playState.generatingTeam&&__playState.teamEditorData?.sets?.filter(Boolean).length===6);const row=await page.evaluate(()=>({format:__playState.format,text:__playState.draft,name:__playState.draftName})),check=await page.evaluate(row=>play.invoke('team-validate',row),row);assert(check.valid,check.errors.join(';'));return row;};
  assert.match(await choose('gen9ru'),/光之黏土/);const ru=await create();assert.equal(ru.format,'gen9ru');await page.locator('.party-slots img').evaluateAll(images=>Promise.all(images.map(n=>n.decode())));
  const next=await create();assert.notEqual(next.text,ru.text,'each New Team changes the generated roster or sets');assert.equal(await page.locator('[data-action=team-starter-use]').count(),0,'no extra accept-sample step');
  const champion=await choose('gen9championsvgc2026regmc');assert.match(champion,/同一道具最多携带 1 个/);assert.match(champion,/出场 4 只/);await create();await page.click('[data-action=team-save]');await page.waitForFunction(()=>!!__playState.editTeamId);await page.click('[data-slot="4"]');await page.waitForFunction(()=>__playState.teamEditorData?.activeIndex===4);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1100,720));await page.locator('#team-format-button').hover();await page.waitForSelector('.dfy-rule-tip:popover-open');assert(await page.locator('.dfy-rule-tip').evaluate(n=>{const r=n.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight;}));await shot('starter-rule-hover');await page.mouse.move(4,4);
  await choose('gen1ou');await create();await page.locator('.page-head [data-action=team-start-blank]').click();await page.waitForFunction(()=>__playState.teamEditorData&&!__playState.draft);await page.click('[data-slot="5"]');assert.equal(await page.locator('.party-editor').getAttribute('data-slot'),'5');
  for(const zoom of [1.25,1.5]){await app.evaluate(({BrowserWindow},zoom)=>{const w=BrowserWindow.getAllWindows()[0];w.webContents.setZoomFactor(zoom);},zoom);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const geometry=await page.evaluate(()=>({width:innerWidth,slots:[...document.querySelectorAll('.party-slot')].map(n=>{const r=n.getBoundingClientRect();return{x:r.x,right:r.right};}),top:document.querySelector('.top-actions').getBoundingClientRect().right}));assert(geometry.slots.every(r=>r.x>=0&&r.right<=geometry.width),JSON.stringify(geometry));assert(geometry.top<=geometry.width,JSON.stringify(geometry));const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG().toString('base64'));fs.writeFileSync(out+'/generated-editor-'+zoom+'.png',Buffer.from(png,'base64'));}
  assert.deepEqual(errors,[]);const result={checks:['one click automatically fills six slots','each new team changes','exact-format hover before choice','champions item clause and full team validation','save then edit fifth slot','bounded tooltip at 1100x720','old-generation team generation','independent empty sixth slot','125 and 150 percent zoom'],errors};fs.writeFileSync(out+'/starter-ui.json',JSON.stringify(result,null,2));console.log(result);
 }catch(error){console.error(error);console.log(await page.evaluate(()=>({format:__playState.format,busy:__playState.teamActionBusy,error:__playState.teamEditorError,draft:__playState.draft?.length,toast:document.querySelector('#toast')?.textContent,pickers:[...document.querySelectorAll('.dfy-format-picker')].map(p=>({open:p.matches(':popover-open'),height:p.offsetHeight})),tip:document.querySelector('.dfy-rule-tip')?.textContent})));await shot('starter-failed');throw error;}finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
