'use strict';
const {app,BrowserWindow,ipcMain,session,safeStorage,protocol}=require('electron'),path=require('path'),fs=require('fs'),{pathToFileURL}=require('url');
protocol.registerSchemesAsPrivileged([{scheme:'dfy-asset',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true,stream:true}}]);
const root=process.env.DFY_PLAY_HOME||(fs.existsSync('E:/Entertainment')?'E:/Entertainment/AppData/ShowdownBattler':path.join(app.getPath('appData'),'ShowdownBattler'));
const cache=process.env.DFY_PLAY_CACHE||(fs.existsSync('E:/Entertainment')?'E:/Entertainment/Caches/ShowdownBattler':path.join(root,'Cache'));process.env.DFY_PLAY_CACHE=cache;
fs.mkdirSync(root,{recursive:true});fs.mkdirSync(cache,{recursive:true});app.setPath('userData',root);app.setPath('sessionData',cache);app.disableHardwareAcceleration();
const {Store}=require('../core/store.cjs'),{Accounts}=require('../core/accounts.cjs'),{ShowdownViews}=require('./showdown.cjs'),{Dex,formats}=require('../core/dex.cjs'),{RuntimeLogger}=require('../core/runtime-log.cjs'),net=require('../core/net.cjs');
const store=new Store(root),logger=new RuntimeLogger(root),accounts=new Accounts(store,safeStorage),dictionary=require('../assets/zh-dictionary.json');let main,web,tick,wantsWeb=false;
process.on('unhandledRejection',error=>logger.error('process.unhandled-rejection',error));
process.on('uncaughtException',error=>logger.error('process.uncaught-exception',error));
if(!fs.existsSync(store.file('settings')))store.saveSettings({audioMuted:false});
else{const existing=store.get('settings',{});if('proxy' in existing||'proxyEnabled' in existing)store.saveSettings(existing);}
const settings=()=>{const s=store.settings();return{server:s.server,chinaUrl:s.chinaUrl,showdownDisplay:s.showdownDisplay,audioMuted:s.audioMuted,audioVolume:s.audioVolume};};
const approved=url=>{try{return ['https://play.pokemonshowdown.com',new URL(settings().chinaUrl).origin].includes(new URL(url).origin);}catch{return false;}};
const send=e=>main&&!main.isDestroyed()&&main.webContents.send('play:event',e);
async function openView(server){const result=await web.open(server);web.layout({visible:wantsWeb});return result;}
async function presentation(wc){if(!approved(wc.getURL()))return;const current=settings();await wc.executeJavaScript('if(!window.__dfyGame){'+require('./showdown-presentation.cjs').script({mode:current.showdownDisplay,playEdition:true})+'}');await wc.executeJavaScript('window.__dfyBattleAudio?.setVolume('+String(current.audioVolume/100)+');');wc.setAudioMuted(current.audioMuted);}
async function mount(view){const wc=view.webContents;try{await presentation(wc);const translation=fs.readFileSync(path.join(__dirname,'../assets/ps-china.user.js'),'utf8');await wc.executeJavaScript(translation.replace('var QQ = $.noConflict();','var QQ = window.jQuery;').replaceAll('NodeFilter.SHOW_Element','(NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT)'));await wc.executeJavaScript('('+require('./page-translator.cjs').mount.toString()+')('+JSON.stringify(require('../core/translation-glossary.cjs').dictionary)+',{terms:true,paragraphs:false})');}catch(e){logger.error('showdown.mount-failed',e);send({type:'error',message:e.message});}}
async function configureSessions(){for(const s of [session.defaultSession,session.fromPartition('persist:showdown-international'),session.fromPartition('persist:showdown-china')]){await require('./battle-asset-protocol.cjs').setup(s,store);await s.setProxy({mode:'direct'});s.setPermissionRequestHandler((a,b,done)=>done(false));}}
const handlers={
 bootstrap:()=>({version:require('../package.json').version,edition:'play',settings:settings(),accounts:accounts.list(),formats:formats().filter(f=>f.search),dictionary,history:store.get('play-history',[]),teams:store.get('teams',[]),teamDraft:store.get('team-draft',{})}),
 ...require('./play-teams.cjs').handlers({store,logger,parent:()=>main,openView,contents:()=>web.views.get(web.active).webContents,server:()=>settings().server}),
 'account-save':p=>{accounts.save({...p,role:'player'});return accounts.list();},'account-delete':p=>accounts.remove(p.id),'account-default':p=>accounts.setDefault(p.id),
 'account-register':p=>require('./play-registration.cjs').register({parent:main,store,input:p}),
 'registration-cancel':()=>require('./play-registration.cjs').cancel(),
 'registration-save':p=>{const value=require('./play-registration.cjs').take(p.token);accounts.save({...value,role:'player',isDefault:!accounts.list().some(a=>a.server===value.server)});return accounts.list();},
 'account-login':async p=>{const c=accounts.credentials(p.id);await openView(c.server);return require('./player-login.cjs').login(web.views.get(c.server).webContents,c);},
 'account-logout':async()=>{const wc=web.views.get(web.active)?.webContents;if(wc)await wc.executeJavaScript('(()=>{if(Object.values(app.rooms).some(r=>r.request?.side&&!r.battle?.ended))throw Error("请先结束当前对局");app.user.logout();})()');return{};},
 'web-open':async p=>{const result=await openView(p.server||settings().server);if(p.retry)await web.reload();return result;},'web-layout':p=>{wantsWeb=!!p.visible;return web.layout(p);},
 'display-mode':async p=>{if(!['game','web'].includes(p.mode))throw Error('未知显示模式');store.saveSettings({showdownDisplay:p.mode});for(const v of web.views.values())if(approved(v.webContents.getURL()))await v.webContents.executeJavaScript('window.__dfyGame?.configure('+JSON.stringify({mode:p.mode})+')');return settings();},
 audio:p=>{const volume=Math.min(100,Math.max(0,Number(p.volume??settings().audioVolume)||0));store.saveSettings({audioMuted:!!p.muted,audioVolume:volume});for(const v of web.views.values()){v.webContents.setAudioMuted(!!p.muted);v.webContents.executeJavaScript('window.__dfyBattleAudio?.setVolume('+String(volume/100)+');').catch(()=>{});}return settings();},
 settings:async p=>{store.saveSettings({server:p.server||settings().server});await configureSessions();return settings();},
 'client-log':p=>{const level=['info','warn','error'].includes(p?.level)?p.level:'error';const event=String(p?.event||'renderer.event').slice(0,120);logger.write(level,event,{message:String(p?.message||'').slice(0,4000),stack:String(p?.stack||'').slice(0,8000),context:p?.context});return{};},
 'export-logs':async()=>{const {dialog}=require('electron');const target=path.join(root,`showdown-battler-log-${new Date().toISOString().replace(/[.:]/g,'-')}.jsonl`);const result=await dialog.showSaveDialog(main,{title:'导出运行日志',defaultPath:target,filters:[{name:'运行日志',extensions:['jsonl','log']}]});if(result.canceled)return null;const file=logger.exportTo(result.filePath);logger.info('runtime.log-exported',{file});return file;},
 ladder:async p=>{const name=String(p.name||'').toLowerCase().replace(/[^a-z0-9]/g,'');if(!name)throw Error('请输入用户名');const rows=await net.json('https://pokemonshowdown.com/users/'+name+'.json',settings());return rows;},
 history:()=>store.get('play-history',[]),
 'history-update':p=>{const rows=store.get('play-history',[]),row=rows.find(r=>r.id===p.id);if(!row)throw Error('记录不存在');if(p.remove){store.set('play-history-hidden',[...new Set([...store.get('play-history-hidden',[]),row.id])]);store.set('play-history',rows.filter(r=>r!==row));}else{row.favorite=!!p.favorite;store.set('play-history',rows);}return store.get('play-history',[]);},
 'history-replay':async p=>{const row=store.get('play-history',[]).find(r=>r.id===p.id);if(!row)throw Error('记录不存在');await openView(row.server);return web.views.get(row.server).webContents.executeJavaScript('('+require('./play-actions.cjs').replay.toString()+')('+JSON.stringify(row)+')');},
 'quick-random':async p=>{await openView(settings().server);const wc=web.views.get(web.active).webContents;return wc.executeJavaScript('('+require('./play-actions.cjs').randomBattle.toString()+')('+JSON.stringify(!!p.cancel)+')');},
 rule:p=>{const f=Dex.formats.get(p.id);if(!f.exists)throw Error('未知规则');const t=Dex.formats.getRuleTable(f);return{id:f.id,name:f.name,gameType:f.gameType||'singles',rules:f.ruleset||[],bans:f.banlist||[],teamSize:t.maxTeamSize,picked:t.pickedTeamSize||t.maxTeamSize,level:t.adjustLevel||t.defaultLevel||100,desc:f.desc||'',threads:f.threads||[]};},
 'web-room':async p=>{if(!/^(?:teambuilder|ladder|battle-[a-z0-9-]+)$/.test(p.room))throw Error('无效房间');await openView(settings().server);const wc=web.views.get(web.active).webContents;await wc.executeJavaScript('window.app?.joinRoom('+JSON.stringify(p.room)+')');return{};}
};
function collect(){if(!web)return;for(const [server,v]of web.views){const wc=v.webContents;if(wc.isDestroyed()||!approved(wc.getURL()))continue;wc.executeJavaScript('(()=>{const text=document.body?.innerText||"";const ipLocked=/currently locked|IP[^\\n]{0,100}locked|被锁定|IP[^\\n]{0,100}封禁/i.test(text);if(!window.app)return{ipLocked};return{ipLocked,user:{name:app.user?.get("name"),named:app.user?.get("named"),searching:!!app.rooms["" ]?.el?.querySelector("button[name=cancelSearch]"),playing:Object.values(app.rooms).some(r=>r.request?.side&&!r.battle?.ended)},games:Object.values(app.rooms).filter(r=>r.battle?.ended).map(r=>({id:r.id,tier:r.battle.tier,p1:r.battle.sides[0]?.name,p2:r.battle.sides[1]?.name,turn:r.battle.turn,lines:r.battle.stepQueue||[]}))};})()').then(async r=>{if(!r)return;if(r.ipLocked)web.checkIpLock(server,wc.getURL());if(!r.user)return;send({type:'user',...r.user,server});if(r.games.length){let history=store.get('play-history',[]),changed=false;for(const g of r.games)if(!g.id.includes('-local')&&!store.get('play-history-hidden',[]).includes(g.id)&&!history.some(h=>h.id===g.id)){history.unshift({...g,server,at:new Date().toISOString(),winner:g.lines.find(l=>String(l).startsWith('|win|'))?.slice(5)||'',lines:g.lines.filter(l=>!String(l).startsWith('|c|')&&!String(l).startsWith('|chat|'))});changed=true;}if(changed){store.set('play-history',history.slice(0,1000));send({type:'history'});}}}).catch(error=>logger.error('showdown.collect-failed',error,{server}));}}
app.whenReady().then(async()=>{await configureSessions();const updater=require('electron-updater').autoUpdater;Object.defineProperty(updater.app,'baseCachePath',{value:cache});await updater.netSession.setProxy({mode:'direct'});updater.logger={info:message=>logger.info('update.info',{message}),warn:message=>logger.warn('update.warning',{message}),error:message=>logger.error('update.error',new Error(String(message)))};
Object.assign(handlers,require('./play-updates.cjs').create({app,updater,shell:require('electron').shell,logger,send,isPlaying:async()=>{for(const v of web?.views.values()||[]){if(!approved(v.webContents.getURL()))continue;const playing=await v.webContents.executeJavaScript('Object.values(window.app?.rooms||{}).some(r=>r.request?.side&&!r.battle?.ended)');if(playing)return true;}return false;}}));main=new BrowserWindow({width:1440,height:930,minWidth:1060,minHeight:720,title:'Showdown对战器',icon:path.join(__dirname,'../assets/icon.ico'),autoHideMenuBar:true,backgroundColor:'#f5f6fa',webPreferences:{preload:path.join(__dirname,'play-preload.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false}});web=new ShowdownViews(main,store,{translate:mount,send,approved,log:(event,data)=>logger.warn(event,data),presentation:()=>require('./showdown-presentation.cjs').script({mode:settings().showdownDisplay,playEdition:true})});ipcMain.handle('play',async(e,key,p)=>{try{if(e.sender!==main.webContents||e.senderFrame!==main.webContents.mainFrame||!handlers[key])throw Error('未授权的操作');return{ok:true,data:await handlers[key](p||{})};}catch(error){logger.error('ipc.failed',error,{method:key});return{ok:false,error:error.message};}});main.webContents.on('console-message',(_,level,message,line,sourceId)=>{if(level>=2)logger.warn('renderer.console',{level,message,line,sourceId});});main.webContents.on('render-process-gone',(_,details)=>logger.error('renderer.process-gone',details));await main.loadURL(pathToFileURL(path.join(__dirname,'../ui/play.html')).href);main.webContents.setWindowOpenHandler(()=>({action:'deny'}));tick=setInterval(collect,2500);main.on('closed',()=>{clearInterval(tick);web.close();main=null;});}).catch(e=>{logger.error('app.start-failed',e);require('electron').dialog.showErrorBox('对战版启动失败',e.message);app.quit();});
app.on('window-all-closed',()=>app.quit());
