'use strict';
if(location.protocol==='https:'&&'serviceWorker' in navigator)navigator.serviceWorker.register('/play-sw.js').catch(()=>{});
const api=(method,payload)=>window.play.invoke(method,payload),$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);let state={page:'battle',user:null,data:null},resize;
const icons={teams:'M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6M17 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6M2 21v-4a6 6 0 0 1 12 0v4m2-7a5 5 0 0 1 6 5v2',battle:'M4 17 17 4m-9 0 12 12M4 4l4 0M4 4v4m12 12v-4m4 4h-4M4 20l4-4m8-8 4-4',accounts:'M20 21v-2a5 5 0 0 0-5-5H9a5 5 0 0 0-5 5v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',history:'M12 4v8l5 3M4 6a9 9 0 1 1-1 10M3 3v5h5',rules:'M4 4h6a3 3 0 0 1 2 2 3 3 0 0 1 2-2h6v15h-6a3 3 0 0 0-2 2 3 3 0 0 0-2-2H4V4m8 2v15'};
function reportClientError(event,error,context={}){const value=error instanceof Error?error:new Error(String(error));api('client-log',{level:'error',event,message:value.message,stack:value.stack,context}).catch(()=>{});}
window.addEventListener('error',event=>{if(event.error||event.message)reportClientError('renderer.error',event.error||event.message,{source:event.filename,line:event.lineno,column:event.colno});});
window.addEventListener('unhandledrejection',event=>reportClientError('renderer.unhandled-rejection',event.reason));
function toast(text,error=false){
 const dialog=$('#dialog'),global=$('#toast');clearTimeout(toast.timer);global.style.display='none';
 if(dialog.open){
  let feedback=dialog.querySelector('.dialog-feedback');if(!feedback){feedback=document.createElement('p');feedback.className='dialog-feedback';const actions=dialog.querySelector('.dialog-actions');if(actions)actions.before(feedback);else dialog.append(feedback);}
  feedback.textContent=text;feedback.classList.toggle('error',error);feedback.setAttribute('role',error?'alert':'status');feedback.hidden=false;feedback.scrollIntoView({block:'nearest'});return;
 }
 global.textContent=text;global.classList.toggle('error',error);global.setAttribute('role',error?'alert':'status');global.style.display='block';toast.timer=setTimeout(()=>global.style.display='none',error?8000:4000);
}
function formatName(name){return String(name).replace(/\[Gen (\d+)\]\s*/,'第 $1 世代 · ').replace('Random Battle','随机单打').replace('Doubles OU','双打 OU').replace('National Dex','全国图鉴').replace('Monotype','同属性').replace('Anything Goes','无限制').replace('Champions','冠军赛');}
function render(){window.DfyTeamEditor?.closeMenu();if(state.page!=='battle')api('web-layout',{visible:false}).catch(()=>{});const d=state.data;$('#app').innerHTML=`<div class="app"><aside class="rail"><div class="brand-ball" title="Showdown对战器"></div>${Object.entries({battle:'对战',teams:'组队',accounts:'账号',history:'战绩',rules:'分级规则'}).map(([id,label])=>`<button class="nav" data-page="${id}" aria-current="${state.page===id}"><svg viewBox="0 0 24 24"><path d="${icons[id]}"></path></svg>${label}</button>`).join('')}<span class="rail-bottom">Showdown · ${esc(d.version)}</span></aside><section class="content"><header class="top"><div class="brand">Showdown<small>对战器</small></div><div class="top-actions"><button class="pill ghost" data-action="account-nav"><i class="status-light"></i><span id="session-name">${esc(state.user?.named?state.user.name:'登录账号')}</span></button><select id="server" class="server" aria-label="服务器"><option value="international" ${d.settings.server==='international'?'selected':''}>国际服</option><option value="china" ${d.settings.server==='china'?'selected':''}>中国服</option></select><button class="pill ghost" data-action="about">关于与更新</button><button class="pill ghost" data-action="network">网络</button><button class="pill ghost" data-action="audio">${d.settings.audioMuted?'声音关':'声音开'}</button></div></header><main class="surface">${page()}</main></section></div>`;requestAnimationFrame(layout);if(state.page==='teams'){window.DfyTeamEditor.restore(state);window.PlayTeams.prepare(state);}if(state.page==='battle')api('web-open',{server:d.settings.server}).catch(e=>toast(e.message,true));}
function page(){const d=state.data;if(state.page==='teams')return window.PlayTeams.render(state);if(state.page==='battle')return `<header class="page-head"><div><h1>对战空间</h1><p>选择队伍，与下一位训练家相遇。</p></div><div class="head-actions"><button class="primary random-start" data-action="random">${state.searching?'取消匹配':'随机对战'}</button><button class="ghost" data-action="team">我的队伍</button><div class="mode-switch" role="group" aria-label="显示模式">${[['game','游戏画面'],['web','原版网页']].map(([m,t])=>`<button data-action="mode" data-mode="${m}" aria-pressed="${d.settings.showdownDisplay===m}">${t}</button>`).join('')}</div></div></header><div id="play-host"><small>正在连接对战服务器…</small></div>`;
 if(state.page==='accounts')return `<header class="page-head"><div><h1>训练家账号</h1><p>在这里管理自己的 Showdown 账号。</p></div><div class="head-actions"><button data-action="register">注册新账号</button><button class="primary" data-action="account-edit">添加已有账号</button></div></header><div class="page-scroll"><div class="grid">${d.accounts.map(a=>`<article class="card"><div class="card-head"><div class="account-avatar">${esc(a.username[0].toUpperCase())}</div>${a.isDefault?'<span class="tag">默认账号</span>':''}</div><h3>${esc(a.label)}</h3><p>${esc(a.username)} · ${a.server==='china'?'中国服':'国际服'}</p><div class="account-actions"><button class="primary" data-action="login" data-id="${esc(a.id)}">登录</button><button data-action="account-edit" data-id="${esc(a.id)}">编辑</button><button data-action="default" data-id="${esc(a.id)}">设为默认</button><button class="ghost danger" data-action="delete" data-id="${esc(a.id)}">移除</button></div></article>`).join('')||'<div class="empty">添加第一个账号，开始对战旅程。</div>'}</div><div class="row" style="margin-top:20px"><button class="ghost" data-action="logout">退出当前登录</button><span class="muted">密码仅保存在本机加密存储中。</span></div></div>`;
 if(state.page==='history')return `<header class="page-head"><div><h1>对战记录</h1><p>查看账号分级积分与本机已完成对局。</p></div><button class="ghost" data-action="history-refresh">刷新</button></header><div class="page-scroll"><div class="query-bar"><input id="ladder-name" aria-label="Showdown 用户名" placeholder="输入 Showdown 用户名" value="${esc(state.user?.named?state.user.name:d.accounts[0]?.username||'')}"><button class="primary" data-action="ladder">查询积分</button></div><div id="ladder-result"></div><section class="card"><h2>最近对局</h2><div class="history-filter"><input id="history-search" placeholder="搜索账号或规则" value="${esc(state.historyQuery||'')}"><label class="checkbox"><input id="history-favorites" type="checkbox" ${state.favorites?'checked':''}>只看收藏</label></div><div id="history-table" style="margin-top:16px">${history()}</div></section></div>`;
 return `<header class="page-head"><div><h1>分级与规则</h1><p>选择适合自己的对战方式。</p></div></header><div class="rules"><aside><input class="format-search" id="rule-search" placeholder="搜索世代、单打、双打…"><div class="rule-list" style="height:calc(100% - 52px)">${d.formats.map(f=>`<button data-action="rule" data-id="${f.id}" data-search="${esc((formatName(f.name)+' '+f.id).toLowerCase())}">${esc(formatName(f.name))}</button>`).join('')}</div></aside><article class="card rule-detail" id="rule-detail"><h2>选择一项规则</h2><p>展示队伍规模、出场数量、对战等级和禁止项目。</p><p>规则来自随程序提供的 Showdown 引擎，实际匹配以服务器校验为准。</p></article></div>`;
}
function history(){const query=(state.historyQuery||'').toLowerCase(),rows=(state.data.history||[]).filter(r=>(!state.favorites||r.favorite)&&[r.p1,r.p2,r.tier,r.winner,formatName(r.tier)].join(' ').toLowerCase().includes(query));return rows.length?'<table class="table"><thead><tr><th>日期</th><th>规则</th><th>训练家</th><th>胜者</th><th>回合</th><th>管理</th></tr></thead><tbody>'+rows.slice(0,100).map(r=>`<tr><td>${esc(new Date(r.at).toLocaleDateString())}</td><td>${esc(formatName(r.tier))}</td><td>${esc(r.p1)} / ${esc(r.p2)}</td><td>${esc(r.winner||'平局')}</td><td>${r.turn||0}</td><td><div class="history-actions"><button data-action="replay" data-id="${esc(r.id)}" ${r.lines?.length?'':'disabled'}>回放</button><button data-action="favorite" data-id="${esc(r.id)}">${r.favorite?'★ 已收藏':'☆ 收藏'}</button><button class="ghost danger" data-action="history-delete" data-id="${esc(r.id)}">删除</button></div></td></tr>`).join('')+'</tbody></table>':'<div class="empty">暂无符合条件的对局。完成的对局会自动保存。</div>';}
function layout(){clearTimeout(resize);resize=setTimeout(()=>{const r=$('#play-host')?.getBoundingClientRect();api('web-layout',{visible:state.page==='battle'&&!$('#dialog').open,bounds:r?{x:r.x,y:r.y,width:r.width,height:r.height}:undefined}).catch(()=>{});},40);}window.__playState=state;window.__playRender=render;window.__playToast=toast;window.__playFormatName=formatName;window.__playModal=modal;window.addEventListener('resize',layout);
async function modal(html){await api('web-layout',{visible:false});clearTimeout(toast.timer);$('#toast').style.display='none';$('#dialog').innerHTML=html;$('#dialog').showModal();layout();}$('#dialog').addEventListener('close',layout);
function showNetworkInfo(){modal('<h2>网络连接</h2><p class="muted">对战器固定使用系统网络直连，不提供本地代理设置。</p><p class="muted">如果 Showdown 仍提示 IP 被锁定，请更换正常网络后重试。</p><div class="dialog-actions"><button type="button" data-action="export-logs">导出运行日志</button><button type="button" data-action="close">关闭</button></div>');}
function showAudioSettings(){const d=state.data.settings;modal(`<h2>声音与音效</h2><form id="audio-form"><label>总音量 <output id="audio-volume-value">${d.audioVolume}%</output><input name="volume" type="range" min="0" max="100" step="5" value="${d.audioVolume}" aria-label="总音量"></label><label class="checkbox"><input name="muted" type="checkbox" ${d.audioMuted?'checked':''}>静音</label><p class="muted">音效、宝可梦叫声和对战背景音乐都会使用此音量。</p><div class="dialog-actions"><button type="button" data-action="close">取消</button><button class="primary">保存</button></div></form>`);}
document.addEventListener('click',event=>{const button=event.target.closest?.('[data-action=network]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();showNetworkInfo();},true);
document.addEventListener('click',async event=>{const button=event.target.closest?.('[data-action=export-logs]');if(!button)return;event.preventDefault();event.stopPropagation();try{const file=await api('export-logs');if(file)toast('运行日志已导出，可提交给开发者');}catch(error){reportClientError('logs.export-failed',error);toast(error.message,true);}},true);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.page){const nextPage=b.dataset.page;window.PlayTeams.capture(state,{tolerant:true}).catch(error=>{reportClientError('team-navigation-save',error);toast('当前配装保存失败：'+error.message,true);});state.page=nextPage;render();return;}if(await window.PlayTeams.action(state,b))return;const a=b.dataset.action;switch(a){case'random':{b.disabled=true;const r=await api('quick-random',{cancel:state.searching});state.searching=r.searching;state.searchRequestedAt=Date.now();b.textContent=r.searching?'取消匹配':'随机对战';toast(r.searching?'正在匹配随机对战，队伍由服务器生成。':'已取消匹配');break;}case'favorite':{const r=state.data.history.find(r=>r.id===b.dataset.id);state.data.history=await api('history-update',{id:r.id,favorite:!r.favorite});$('#history-table').innerHTML=history();break;}case'history-delete':modal('<h2>删除这条对战记录？</h2><p>仅删除本机记录与回放。</p><div class="dialog-actions"><button data-action="close">取消</button><button class="danger" data-action="history-remove" data-id="'+esc(b.dataset.id)+'">删除</button></div>');break;case'history-remove':state.data.history=await api('history-update',{id:b.dataset.id,remove:true});$('#dialog').close();$('#history-table').innerHTML=history();break;case'replay':{const row=state.data.history.find(r=>r.id===b.dataset.id);state.data.settings.server=row.server;await api('settings',{server:row.server});state.page='battle';render();await api('history-replay',{id:row.id});break;}case'account-nav':state.page='accounts';render();break;case'mode':b.disabled=true;state.data.settings=await api('display-mode',{mode:b.dataset.mode});for(const n of document.querySelectorAll('[data-action=mode]'))n.setAttribute('aria-pressed',String(n.dataset.mode===b.dataset.mode));break;case'about':await showAbout();break;case'update-check':case'update-download':case'update-install':b.disabled=true;renderUpdate(await api(a));break;case'project-open':await api('project-open');break;case'audio':showAudioSettings();break;case'web-retry':b.disabled=true;$('#play-host').innerHTML='<small>正在重新连接对战服务器…</small>';await api('web-open',{server:state.data.settings.server,retry:true});break;case'team':state.page='teams';render();break;case'network':showNetworkInfo();break;
 case'register':modal('<h2>注册训练家账号</h2><form id="register-form"><label>用户名<input name="username" required maxlength="19" autocomplete="username" placeholder="1–19 位英文、数字或空格"></label><label>密码<input name="password" type="password" required minlength="5" autocomplete="new-password"></label><label>确认密码<input name="confirm" type="password" required minlength="5" autocomplete="new-password"></label><label>服务器<select name="server"><option value="international">国际服</option><option value="china">中国服</option></select></label><p class="muted">下一步完成服务器验证。注册成功后，可一键保存到账号管理。</p><div class="dialog-actions"><button type="button" data-action="close">取消</button><button class="primary">继续注册</button></div></form>');break;case'registration-save':state.data.accounts=await api('registration-save',{token:b.dataset.token});$('#dialog').close();state.page='accounts';render();toast('注册账号已加密保存，可直接登录');break;case'account-edit':{const row=state.data.accounts.find(a=>a.id===b.dataset.id)||{};modal(`<h2>${row.id?'编辑账号':'添加账号'}</h2><form id="account-form"><input type="hidden" name="id" value="${esc(row.id||'')}"><label>名称<input name="label" value="${esc(row.label||'')}" placeholder="我的账号"></label><label>用户名<input name="username" required maxlength="19" autocomplete="username" value="${esc(row.username||'')}" placeholder="1–19 位英文、数字、空格、下划线或连字符"></label><label>密码<input name="password" type="password" ${row.id?'':'required'} autocomplete="new-password" placeholder="${row.id?'留空保留原密码':'账号密码'}"></label><label>服务器<select name="server"><option value="international">国际服</option><option value="china" ${row.server==='china'?'selected':''}>中国服</option></select></label><label class="checkbox"><input type="checkbox" name="isDefault" ${row.isDefault?'checked':''}>设为默认</label><div class="dialog-actions"><button type="button" data-action="close">取消</button><button class="primary">保存</button></div></form>`);break;}
 case'close':$('#dialog').close();break;case'login':{b.disabled=true;toast('正在登录…');const r=await api('account-login',{id:b.dataset.id});state.user={name:r.username,named:true};state.data.settings.server=state.data.accounts.find(a=>a.id===b.dataset.id).server;await api('settings',{server:state.data.settings.server});state.page='battle';render();toast('已登录 '+r.username);break;}case'logout':await api('account-logout');state.user=null;toast('已退出登录');break;case'default':state.data.accounts=await api('account-default',{id:b.dataset.id});render();break;case'delete':modal(`<h2>移除这个账号？</h2><p class="muted">只移除本机保存的登录信息。</p><div class="dialog-actions"><button data-action="close">取消</button><button class="danger" data-action="delete-confirm" data-id="${esc(b.dataset.id)}">移除</button></div>`);break;case'delete-confirm':state.data.accounts=await api('account-delete',{id:b.dataset.id});$('#dialog').close();render();break;
 case'ladder':{b.disabled=true;const r=await api('ladder',{name:$('#ladder-name').value}),rows=Object.entries(r.ratings||{});$('#ladder-result').innerHTML='<section class="card" style="margin-bottom:18px"><h2>'+esc(r.username||r.userid||'积分')+'</h2>'+(rows.length?'<table class="table"><thead><tr><th>规则</th><th>Elo</th><th>GXE</th><th>胜 / 负</th></tr></thead><tbody>'+rows.map(([id,v])=>`<tr><td>${esc(formatName(id))}</td><td>${Math.round(v.elo||1000)}</td><td>${esc(v.gxe||'—')}</td><td>${esc(v.w||0)} / ${esc(v.l||0)}</td></tr>`).join('')+'</tbody></table>':'<p>该账号暂无公开积分。</p>')+'</section>';break;}case'history-refresh':state.data.history=await api('history');render();break;
 case'rule':{const r=await api('rule',{id:b.dataset.id});const tr=x=>state.data.dictionary[x]||x;$('#rule-detail').innerHTML=`<h2>${esc(formatName(r.name))}</h2><div class="rule-chips"><span>${r.gameType==='doubles'?'双打':'单打'}</span><span>队伍 ${r.teamSize} 只</span><span>出场 ${r.picked} 只</span><span>${r.level} 级</span></div><h3>规则条款</h3><ul>${r.rules.map(x=>'<li>'+esc(tr(x))+'</li>').join('')}</ul><h3>禁止项目</h3><p>${r.bans.length?r.bans.map(x=>esc(tr(x))).join('、'):'无额外禁止项目'}</p>`;break;}
 }}catch(e){toast(e.message,true);}finally{if(b.dataset.action!=='team-resource-retry')b.disabled=false;}});
document.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const feedback=e.target.querySelector('.dialog-feedback');if(feedback)feedback.hidden=true;const submitter=e.submitter;if(submitter)submitter.disabled=true;try{if(e.target.getAttribute('id')==='register-form'){const submit=e.target.querySelector('.primary');submit.disabled=true;try{const r=await api('account-register',data);$('#dialog').close();await modal('<h2>注册成功</h2><p>'+esc(r.username)+' 已通过服务器确认。</p><div class="dialog-actions"><button data-action="close">稍后保存</button><button class="primary" data-action="registration-save" data-token="'+esc(r.token)+'">一键保存到账号管理</button></div>');}finally{submit.disabled=false;}}else if(e.target.getAttribute('id')==='account-form'){data.isDefault=!!data.isDefault;state.data.accounts=await api('account-save',data);$('#dialog').close();render();toast('账号已加密保存');}else if(e.target.getAttribute('id')==='audio-form'){state.data.settings=await api('audio',{muted:!!data.muted,volume:Number(data.volume)});$('#dialog').close();render();toast(state.data.settings.audioMuted?'声音已关闭':'声音设置已保存');}}catch(e){toast(e.message,true);}finally{if(submitter)submitter.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='history-search'){state.historyQuery=e.target.value;$('#history-table').innerHTML=history();}if(e.target.id==='rule-search'){const q=e.target.value.toLowerCase();for(const b of document.querySelectorAll('[data-search]'))b.hidden=!b.dataset.search.includes(q);}if(e.target.name==='volume'&&e.target.form?.id==='audio-form'){const out=$('#audio-volume-value');if(out)out.textContent=e.target.value+'%';}});
document.addEventListener('change',async e=>{if(e.target.id==='history-favorites'){state.favorites=e.target.checked;$('#history-table').innerHTML=history();}if(e.target.id==='server')try{state.data.settings=await api('settings',{server:e.target.value});state.user=null;render();}catch(e){toast(e.message,true);}});
window.play.onEvent(e=>{if(e.type==='user'&&e.server===state.data?.settings.server){state.user=e;if(e.playing||e.searching||Date.now()-(state.searchRequestedAt||0)>10000){state.searching=!!e.searching&&!e.playing;const queue=document.querySelector('[data-action=random]');if(queue)queue.textContent=state.searching?'取消匹配':'随机对战';}const n=$('#session-name');if(n)n.textContent=e.named?e.name:'登录账号';}if(e.type==='error')toast(e.message,true);if(e.type==='history')api('history').then(r=>state.data.history=r);});
window.play.onEvent(e=>{if(e.type==='update')renderUpdate(e);if(e.type==='network-lock')toast('Showdown 锁定了当前 IP，请更换正常网络后重试。',true);});
window.play.onEvent(e=>{if(e.type!=='web-status'||e.server!==state.data?.settings.server)return;const host=$('#play-host');if(e.error){if(host)host.innerHTML='<div class="connection-error"><strong>暂时无法连接 Showdown</strong><p>'+esc(e.error)+'</p><button class="primary" data-action="web-retry">重试连接</button><small>组队、图鉴和已缓存素材仍可离线使用。</small></div>';toast(`对战页面连接失败：${e.error}`,true);}else if(e.loaded&&host)host.innerHTML='<small>正在装载对战界面…</small>';});
api('bootstrap').then(d=>{state.data=d;render();}).catch(e=>toast(e.message,true));

async function showAbout(){const info=await api('update-status');await modal('<h2>Showdown 对战器</h2><p>版本 '+esc(info.version)+' · 作者：白月遥</p><p>特别鸣谢 <strong>loving1096</strong>。遇到问题可以联系他，并向他提供运行日志和复现步骤。</p><p class="muted">本软件仅供交流，免费使用，不涉及任何商业行为。</p><p class="muted">GitHub：whitemoon105/showdown-battler</p><div id="update-status" role="status"></div><div class="dialog-actions"><button data-action="export-logs">导出运行日志</button><button data-action="project-open">公开仓库</button><button data-action="update-check">检查更新</button><button id="update-next" class="primary" hidden></button><button data-action="close">关闭</button></div>');renderUpdate(info);}
function renderUpdate(info){const target=$('#update-status');if(!target)return;target.textContent=info.message||'可从公开仓库获取新版本，更新会保留账号、队伍与战绩。';const check=$('[data-action=update-check]');if(check)check.disabled=['checking','downloading','installing'].includes(info.phase);const next=$('#update-next');if(next){next.hidden=!['available','ready'].includes(info.phase);next.disabled=false;next.dataset.action=info.phase==='ready'?'update-install':'update-download';next.textContent=info.phase==='ready'?'重启并安装':'下载更新';}}
